<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- 
        promise错误穿透: 底层原理：reason => {throw reason}
            你自己没指定失败的回调 但是底层抛出错误回调 层层传递 最后传到最后一个catch中
            (1)当使用promise的then链式调用时，可以在最后用catch指定一个失败的回调，
            (2)前面任何操作出了错误，都会传到最后失败的回调中处理了
        备注:如果不存在then的链式调用。就不需要考虑then的错误穿透。

    -->
    <script>
        function sendAjax(url, data) {
            return new Promise((resolve, reject) => {
                const xhr = new XMLHttpRequest();
                xhr.onreadystatechange = () => {
                    if (xhr.readyState === 4) {
                        if (xhr.status >= 200 && xhr.status < 300) {
                            resolve(xhr.response)
                        } else {
                            reject('失败了!')
                        }
                    }
                }
                let str = '';
                for (const key in data) {
                    str += `${key}=${data[key]}&`
                }
                str = str.slice(0, -1)
                xhr.open('GET', url + '?' + str)
                xhr.responseType = 'json'
                xhr.send()
            })
        }
        // 第一次请求
        sendAjax('https://api.uixsj.cn/hitokoto/get', { type: 'hitokoto', code: 'json' })
            .then(
                value => {
                    console.log('第1次成功了', value);
                    return sendAjax('https://api.uixsj.cn/hitokoto/get', { type: 'hitokoto', code: 'json' })
                },
                // reason => { console.log('第1次失败了', reason); return new Promise(() => { }) }
            )
            .then(
                value => {
                    console.log('第2次成功了', value);
                    return sendAjax('https://api.uixsj.cn/hitokoto/get', { type: 'hitokoto', code: 'json' })
                },
                // reason => { console.log('第2次失败了', reason); return new Promise(() => { }) }
            )
            .then(
                value => {
                    console.log('第3次成功了', value);
                    return sendAjax('https://api.uixsj.cn/hitokoto/get', { type: 'hitokoto', code: 'json' })
                },
                // reason => { console.log('第3次失败了', reason) }
            ).catch(
                reason => { console.log('失败了', reason) }
            )
    </script>
</body>

</html>